package golite.semantic.symbol;

import golite.semantic.type.AliasType;
import golite.semantic.type.Type;
import golite.util.SourcePositioned;

/**
 * The symbol generated by a type declaration.
 */
public class DeclaredType<T extends Type> extends Symbol<T> {
    private final T type;

    public DeclaredType(String name, T type) {
        super(name);
        this.type = type;
    }

    public DeclaredType(SourcePositioned source, String name, T type) {
        this(source.getStartLine(), source.getEndLine(), source.getStartPos(), source.getEndPos(), name, type);
    }

    public DeclaredType(int startLine, int endLine, int startPos, int endPos, String name, T type) {
        super(startLine, endLine, startPos, endPos, name);
        this.type = type;
    }

    @Override
    public T getType() {
        return type;
    }

    @Override
    public String toString() {
        if (type instanceof AliasType) {
            return String.format("type %s %s", name, ((AliasType) type).getInner());
        }
        return "type " + type;
    }
}
