/*
 * This file is part of GoLite, licensed under the MIT License (MIT).
 *
 * Copyright (c) 2017 Aleksi Sapon, Rohit Verma, Ayesha Krishnamurthy <https://github.com/DDoS/Golite>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package golite.semantic.symbol;

import golite.semantic.check.TypeCheckerException;
import golite.semantic.type.FunctionType;
import golite.semantic.type.Type;
import golite.util.SourcePositioned;

/**
 * The symbol generated by a variable declaration.
 */
public class Variable<T  extends Type> extends Symbol<T> {
    private final Variable<T> aliasedOriginal;
    private final T type;

    public Variable(SourcePositioned source, String name, T type) {
        this(source.getStartLine(), source.getEndLine(), source.getStartPos(), source.getEndPos(), name, type);
    }

    public Variable(int startLine, int endLine, int startPos, int endPos, String name, T type) {
        this(null, startLine, endLine, startPos, endPos, name, type);
    }

    private Variable(Variable<T> aliasedOriginal, int startLine, int endLine, int startPos, int endPos, String name, T type) {
        super(startLine, endLine, startPos, endPos, name);
        this.aliasedOriginal = aliasedOriginal;
        this.type = type;
        if (type instanceof FunctionType) {
            throw new TypeCheckerException(this, "Cannot have a variable with a function type");
        }
    }

    @Override
    public T getType() {
        return type;
    }

    public Variable<T> dealias() {
        if (aliasedOriginal != null) {
            return this;
        }
        @SuppressWarnings("unchecked")
        final T resolvedType = (T) type.deepResolve();
        return new Variable<>(this, getStartLine(), getEndLine(), getStartPos(), getEndPos(), name, resolvedType);
    }

    @Override
    public String toString() {
        return String.format("var %s %s", name, type);
    }

    @Override
    public boolean equals(Object object) {
        if (!(object instanceof Variable<?>)) {
            return false;
        }
        final Variable<?> that = (Variable<?>) object;
        final Variable<?> a = this.aliasedOriginal != null ? this.aliasedOriginal : this;
        final Variable<?> b = that.aliasedOriginal != null ? that.aliasedOriginal : that;
        return a == b;
    }

    @Override
    public int hashCode() {
        return aliasedOriginal != null ? aliasedOriginal.hashCode() : super.hashCode();
    }
}
