package ca.sapon.golite.semantic.symbol;

import ca.sapon.golite.semantic.type.Type;
import ca.sapon.golite.util.SourcePositioned;

/**
* The symbol generated by a variable declaration.
 */
public class Variable extends Symbol {
    private final Type type;
    private boolean constant;

    public Variable(String name, Type type, boolean constant) {
        super(name);
        this.type = type;
        this.constant = constant;
    }

    public Variable(SourcePositioned source, String name, Type type, boolean constant) {
        this(source.getStartLine(), source.getEndLine(), source.getStartPos(), source.getEndPos(), name, type, constant);
    }

    public Variable(int startLine, int endLine, int startPos, int endPos, String name, Type type, boolean constant) {
        super(startLine, endLine, startPos, endPos, name);
        this.type = type;
        this.constant = constant;
    }

    @Override
    public Type getType() {
        return type;
    }

    public boolean isConstant() {
        return constant;
    }

    @Override
    public String toString() {
        return String.format("var %s %s", name, type);
    }
}
