package golite.semantic;

import java.util.Collections;
import java.util.Comparator;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Optional;
import java.util.Set;
import java.util.TreeMap;

import golite.node.AFuncDecl;
import golite.node.Node;
import golite.node.PExpr;
import golite.semantic.context.Context;
import golite.semantic.symbol.Function;
import golite.semantic.symbol.Variable;
import golite.semantic.type.Type;
import golite.util.NodePosition;
import golite.util.SourcePrinter;

/**
 * The data generated by the type-checker. This includes the type of expressions and the code contexts.
 */
public class SemanticData {
    public static SemanticData EMPTY = new SemanticData(Collections.emptyMap(), Collections.emptyMap(),
            Collections.emptyMap(), Collections.emptyMap());
    private final Map<PExpr, Type> exprNodeTypes;
    private final Map<Context, Node> contextNodes;
    private final Map<AFuncDecl, Function> funcSymbols;
    private final Map<Node, Set<Variable>> varSymbols;

    public SemanticData(Map<PExpr, Type> exprNodeTypes, Map<Context, Node> contextNodes, Map<AFuncDecl,
            Function> funcSymbols, Map<Node, Set<Variable>> varSymbols) {
        this.exprNodeTypes = exprNodeTypes;
        this.contextNodes = contextNodes;
        this.funcSymbols = funcSymbols;
        this.varSymbols = varSymbols;
    }

    public Optional<Type> getExprType(PExpr expr) {
        return Optional.ofNullable(exprNodeTypes.get(expr));
    }

    public Optional<Function> getFunctionSymbol(AFuncDecl node) {
        return Optional.ofNullable(funcSymbols.get(node));
    }

    public void printContexts(SourcePrinter printer, boolean all) {
        // The contexts are serially ID'd, so we can sort them by ID to get the order in which they were entered
        final TreeMap<Context, Node> sortedContextNodes = new TreeMap<>(Comparator.comparingInt(Context::getID));
        sortedContextNodes.putAll(contextNodes);
        // Iterate the context, and print them with the node information
        for (Entry<Context, Node> contextNode : sortedContextNodes.entrySet()) {
            printer.print("########################################").newLine();
            if (all) {
                contextNode.getKey().printAll(printer);
            } else {
                contextNode.getKey().print(printer);
            }
            printer.print("@").print(new NodePosition(contextNode.getValue()).positionToString()).newLine();
        }
    }
}
